### ISSUE TITLE
Distributions Gallery: Normal

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#475]
Add these distributions to "see also". 

* TruncatedNormal
* VoMises (because is like a normal but on the circle)
* Logistic (because it "looks like a normal" and is sometimes used as a robust alternative)

What about these two? They are related to the normal, but not that close in the "prior-space" 

* HalfNormal
* LogNormal

**Comment by OriolAbril** [comment]
We could have different sections/boxes instead of only a "see also". For example: "common alternatives", where we list a distribution with a link to the corresponding preliz page and then a single line with the main difference, and "related distributions"/keep the see also, with a more flexible format.
